---
- name: Install kubelet kubeadm kubectl
  hosts: k8s
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  tasks:
    - name: Run install script
      script: ~/code/Ansible/files/install_kubeapps.sh