---
- name: Deploy www.ycdisp.com
  hosts: yc-srv1
  gather_facts: no
  # remote_user: eingram
  become_user: poduser
  become_method: sudo

  vars:
    app: "www.ycdisp.com"
    root: '/home/poduser/code/'
    repo: 'git@github.com:eingram23/'
    mysql_root: "{{ lookup('hashi_vault','secret=secret/data/ycprod/mysql:root') }}"
    mysql_yandcprod: "{{ lookup('hashi_vault','secret=secret/data/ycprod/mysql:yandcprod') }}"
    nginx_port: "8080"
    
  # pre_tasks:

  #     - name: Remind to enable linger for poduser
  #       pause:
  #         prompt: "sudo loginctl enable-linger as poduser [hit enter to continue]"

  roles:
    - common

  