---
- name: Create supporting folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0775
  loop:
    - "{{root}}"
    - /home/poduser/.ssh
    # - /home/poduser/.config/systemd/user

- name: Copy github private key to remote host
  ansible.builtin.copy:
    src: ssh-key-ansible.key
    dest: /home/poduser/.ssh/
    mode: '0600'

# - name: Pause playbook until web files are uploaded to host
#   pause:
#     prompt: "Make sure web file backup is in /home/poduser and renamed to sitebackup.tar.gz"
    
- name: Clone www.ycdisp.com repo from github
  git:
    repo: "{{repo}}{{app}}.git"
    dest: "{{root}}{{app}}"
    clone: yes
    key_file: /home/poduser/.ssh/ssh-key-ansible.key
    accept_hostkey: yes
    update: yes
    force: yes

# - name: Extract web files to html root
#   ansible.builtin.unarchive:
#     src: /home/poduser/sitebackup.tar.gz
#     dest: "{{root}}"
#     remote_src: yes
#     extra_opts: [--strip-components=2]

# - name: Modify html perms to make necessary folders writable
#   ansible.builtin.file:
#     path: "{{item}}"
#     state: directory
#     recurse: yes
#     mode: '0777'
#   loop:
#     - "{{root}}{{app}}/public_html/attachments"
#     - "{{root}}{{app}}/public_html/avatars"
#     - "{{root}}{{app}}/public_html/cache"
#     - "{{root}}{{app}}/public_html/Packages"
#     - "{{root}}{{app}}/public_html/Smileys"
#     - "{{root}}{{app}}/public_html/Themes"

- name: Clone Containers repo from github
  git:    
    repo: "{{repo}}Containers.git"
    dest: "{{root}}Containers"
    key_file: /home/poduser/.ssh/ssh-key-ansible.key
    accept_hostkey: yes
    clone: yes
    update: yes

- name: Build www.ycdisp.com-web image
  containers.podman.podman_image:
    name: "{{app}}-web"
    path: "{{root}}Containers/Projects/{{app}}/{{app}}-web"
    force: yes

# - name: Pause playbook to make sure smfprod sql dump is on remote host
#   pause:
#     prompt: "Make sure smfprod backup is in /home/poduser and renamed to smfprod.bak.gz"

- name: Copy sql backup to build Location
  ansible.builtin.copy:
    src: yandcprod.sql
    dest: "{{root}}Containers/Projects/{{app}}/{{app}}-db"

# - name: Extract smfprod sql backup
#   ansible.builtin.shell: gunzip -c /home/poduser/smfprod.bak.gz > {{root}}Containers/Projects/{{app}}/{{app}}-db/smfprod.sql

- name: Build www.ycdisp.com-db image
  containers.podman.podman_image:
    name: "{{app}}-db"
    path: "{{root}}Containers/Projects/{{app}}/{{app}}-db"
    force: yes

- name: Create www.ycdisp.com pod
  containers.podman.podman_pod:
    name: "{{app}}"
    state: started
    publish: "127.0.0.1:{{nginx_port}}:{{nginx_port}}"

- name: Run www.ycdisp.com-web container
  containers.podman.podman_container:
    name: "{{app}}-web"
    image: localhost/{{app}}-web
    volume: 
      - "{{root}}{{app}}/public_html:/var/www/html:z"
    state: started
    restart_policy: always
    pod: "{{app}}"

- name: Run www.ycdisp.com-db container
  containers.podman.podman_container:
    name: "{{app}}-db"
    image: localhost/{{app}}-db
    env:
      MYSQL_ROOT_PASSWORD: "{{mysql_root}}"
      MYSQL_DATABASE: yandcprod
      MYSQL_USER: yandcprod
      MYSQL_PASSWORD: "{{mysql_yandcprod}}"
    volume: 
      - yandcprod-data:/var/lib/mysql
    state: started
    restart_policy: always
    pod: "{{app}}"


    
    