---
- name: Install nginx
  package:
    name: "nginx"
    state: present

- name: Copy proxy.conf to /etc/nginx/conf.d
  ansible.builtin.copy:
    src: proxy.conf
    dest: /etc/nginx/conf.d
    mode: '0644'

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
