---
- hosts: "{{ hosts_prompt }}"
  remote_user: eingram
  become: yes
  become_method: sudo

  vars_prompt:
    - name: "hosts_prompt"
      prompt: "hostname or host group need to run with Playbook"
      private: no

  tasks:
    - when: ansible_facts['distribution'] != 'CentOS'
      block:
        - name: Check if reboot required (Debian)
          stat:
            path: "/var/run/reboot-required"
          register: reboot_required_data
        
        - name: Report if reboot required
          debug:
            msg: "Reboot required"
          when: reboot_required_data.stat.exists

        - name: Report if reboot not required
          debug:
            msg: "Reboot not required"
          when: not reboot_required_data.stat.exists
 
    - when: ansible_facts['distribution'] == 'CentOS'
      block:
        - name: Install yum-utils (if needed)
          package:
            name: yum-utils

        - name: Check if reboot required (CentOS)
          shell: needs-restarting -r
          failed_when: false
          register: reboot_required
          changed_when: false
