---
- hosts: gcp
  gather_facts: yes
  remote_user: eingram
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
#    - "{{ ansible_distribution_major_version }}"
