---
- name: Get IP address of host
  hosts: "{{ host }}"
  remote_user: eingram
  gather_facts: yes

  vars_prompt:
    - name: "host"
      prompt: "Enter hostname"
      private: no

  tasks:
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
      
