---
- name: Get host
  hosts: localhost pihole
  gather_facts: no
  vars_prompt:
    - name: "host_prompt"
      prompt: "Enter host to remove"
      private: no

  tasks:
    - set_fact:
        host: "{{ host_prompt }}"

- name: Remove host from Ansible inventory
  hosts: localhost
  gather_facts: no
  connection: local
  become: false

  tasks:
    - name: Remove inventory entry
      lineinfile:
        backup: yes
        path: ~/code/Ansible/hosts
        line: "{{ host }}"
        state: absent

    - meta: refresh_inventory
    
- name: Remove host record to piholes
  hosts: pihole
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  tasks:

    - name: Remove DNS record
      lineinfile:
        backup: yes
        path: /etc/pihole/custom.list
        regexp: "{{ host }}$"
        state: absent

    - name: Restart pihole-FTL
      service:
        name: pihole-FTL
        state: restarted
