---
- name: Remove host from Ansible inventory
  hosts: localhost
  gather_facts: no
  connection: local
  become: false

  vars_prompt:
    - name: "host"
      prompt: "Enter host to remove"
      private: no

  tasks:

    - name: Remove inventory entry
      lineinfile:
        backup: yes
        path: ~/code/Ansible/hosts
        line: "{{ host }}"
        state: absent

    - name: Refresh metadata
      meta: refresh_inventory
    
- name: Remove host record to piholes
  hosts: pihole
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  tasks:

    - name: Remove DNS record
      lineinfile:
        backup: yes
        path: /etc/pihole/custom.list
        line: "{{ ansible_facts['ansible_default_ipv4.address'] }} {{ host }}"
        state: absent

    - name: Restart pihole-FTL
      service:
        name: pihole-FTL
        state: restarted
