---
- name: Configure firewalld for unifi
  hosts: "{{ host }}"
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  tasks:
    - name: Open required ports for Unifi Controller
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        zone: public
      loop:
        - 3478/udp
        - 10001/udp
        - 8080/tcp
        - 8443/tcp
        - 1900/udp
        - 8843/tcp
        - 8880/tcp
        - 6789/tcp
        - 5514/tcp
      
  