---
# - name: set fact
#   set_fact:
#     test_list: "{{ ip_address_list | length}}"

# - when: test_list == "1"
#   block:
#     - name: set ip_address
#       set_fact:
#         ip_address: "{{ip_address_list[0]}}"

#     - name: set vm_name
#       set_fact:
#         vm_name: "{{vm_name_list[0]}}.{{dns_suffix_list[0]}}"

#     - name: Add DNS records to Pihole (single host)
#       lineinfile:
#         backup: yes
#         path: /etc/pihole/custom.list
#         line: "{{ip_address}} {{vm_name}}"
#         state: present
#       register: dns_changed

#     - name: Restart pihole-FTL
#       service:
#         name: pihole-FTL
#         state: restarted
#       when: dns_changed.changed

#     - meta: end_play

# - name: debug
#   debug:
#     msg: "{{ip_address_list}}"

# - name: debug2
#   debug:
#     msg: "{{vm_name_list}}"

- name: combine ip_address_list and vm_name_list list
  set_fact:
    dns_entry: "{{ip_address_list | zip(vm_name_list) | map('join', ' ') | list }}"

- name: Add DNS records to Pihole (multiple hosts)
  lineinfile:
    backup: yes
    path: /etc/pihole/custom.list
    line: "{{ item }}.{{dns_suffix_list[0]}}"
    state: present
  loop: "{{dns_entry}}"
  register: dns_changed

- name: Restart pihole-FTL
  service:
    name: pihole-FTL
    state: restarted
  when: dns_changed.changed

