---
- name: Install Podman
  become: true
  become_method: sudo
  package:
    name: "podman"
    state: present
    
- name: Allow lingering (for rootless podman)
  shell: "loginctl enable-linger"

- name: Create supporting folder structure
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: eingram
    group: eingram
    mode: 0775
  loop:
    - /home/eingram/code
    - /home/eingram/.config/systemd/user

- name: Clone test.diversionforum.net repo from github
  git:
    repo: "{{repo}}{{app}}.git"
    dest: "{{root}}{{app}}"
    clone: yes
    update: yes
    force: yes

- name: Add db password to Settings.php
  ansible.builtin.lineinfile:
    path: "{{root}}{{app}}/html/Settings.php"
    search_string: 'changethis'
    line: $db_passwd = '{{mysql_df}}';

- name: Modify html perms to make necessary folders writable
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    recurse: yes
    mode: '0777'
  loop:
    - "{{root}}{{app}}/html/attachments"
    - "{{root}}{{app}}/html/avatars"
    - "{{root}}{{app}}/html/cache"
    - "{{root}}{{app}}/html/Packages"
    - "{{root}}{{app}}/html/Smileys"
    - "{{root}}{{app}}/html/Themes"

- name: Clone Containers repo from github
  git:    
    repo: "{{repo}}Containers.git"
    dest: "{{root}}Containers"
    clone: yes
    update: yes

- name: Build test.diversionforum.net-web image
  containers.podman.podman_image:
    name: "{{app}}-web"
    path: "{{root}}Containers/Projects/{{app}}/{{app}}-web"
    force: yes

- name: Build test.diversionforum.net-php image
  containers.podman.podman_image:
    name: "{{app}}-php"
    path: "{{root}}Containers/Projects/{{app}}/{{app}}-php"
    force: yes

- name: Copy sql backup to build Location
  ansible.builtin.copy:
    src: smfprod.sql
    dest: "{{root}}Containers/Projects/{{app}}/{{app}}-db"

- name: Build test.diversionforum.net-db image
  containers.podman.podman_image:
    name: "{{app}}-db"
    path: "{{root}}Containers/Projects/{{app}}/{{app}}-db"
    force: yes

- name: Create test.diversionforum.net pod
  containers.podman.podman_pod:
    name: "{{app}}"
    state: started
    publish: 8080:8080

- name: Run test.diversionforum.net-web container
  containers.podman.podman_container:
    name: "{{app}}-web"
    image: localhost/{{app}}-web
    volume: 
      - "{{root}}{{app}}/html:/var/www/html:z"
    state: started
    restart_policy: always
    pod: "{{app}}"

- name: Run test.diversionforum.net-php container
  containers.podman.podman_container:
    name: "{{app}}-php"
    image: localhost/{{app}}-php
    volume: 
      - "{{root}}{{app}}/html:/var/www/html"
    state: started
    restart_policy: always
    pod: "{{app}}"

- name: Run test.diversionforum.net-db container
  containers.podman.podman_container:
    name: "{{app}}-db"
    image: localhost/{{app}}-db
    env:
      MYSQL_ROOT_PASSWORD: "{{mysql_root}}"
      MYSQL_DATABASE: smfprod
      MYSQL_USER: smfprod
      MYSQL_PASSWORD: "{{mysql_smfprod}}"
    volume: 
      - /var/lib/mysql
    state: started
    restart_policy: always
    pod: "{{app}}"


    
    