- name: Install windows Exporter
  hosts: "{{ hostvar|default([]) }}"
  gather_facts: false
  become: true

  tasks:

    - name: Create program folder
      ansible.windows.win_file:
        path: C:\Program Files\windows_exporter
        state: directory

    - name: Copy config file
      ansible.windows.win_copy:
        src: config.yml
        dest: C:\Program Files\windows_exporter\config.yml

    - name: Copy windows_exporter installer to remote system
      ansible.windows.win_copy:
        src: windows_exporter-0.18.1-amd64.msi
        dest: C:\temp\

    - name: Install windows_exporter
      ansible.windows.win_package:
        path: C:\temp\windows_exporter-0.18.1-amd64.msi
        product_id: '{F6DCD1DB-A703-47EA-BEFF-7064DD34C2FC}'
        arguments: 'EXTRA_FLAGS="--config.file=""C:\Program Files\windows_exporter\config.yml"""'
        state: present

- name: Add target to prometheus server
  hosts: grafana.local.lan
  gather_facts: false
  become: yes
  become_method: sudo

  tasks:

    - name: Add entry to prometheus.yml
      ansible.builtin.lineinfile:
        path: /etc/prometheus/prometheus.yml
        insertafter: "      - targets: ['localhost:9100']"
        line: "      - targets: ['{{hostvar}}:9182']"

    - name: Restart prometheus
      ansible.builtin.service:
        name: prometheus
        state: restarted

