---
- name: Run terraform destroy and clean inventory/dns
  hosts: pihole
  gather_facts: false
  remote_user: eingram
  become: true
  become_method: sudo
  vars_files:
    - vars.yaml
  
  roles:
    - pihole_remove

- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  roles:
    - remove_hosts_inv
    - terraform_destroy
    - remove_known_hosts
 