---

tf_root: /Users/edwardingram/code/Terraform/
temp_path: "{{tf_root}}/Templates/vsphere_win_wg/"
proj_root: "{{tf_root}}/Projects/"
proj_name: WinTest

# Edit this to change distro
vsphere_template: TMP-Win2022Core_Packer_2022_04

vm_ram: 4096
vm_cpu: 2

# Do not change
ansible_group: windows

dns_suffix_list: 
  - local.lan
workgroup: WORKGROUP

# All lists must have same # of elements

vm_name_list: 
  - wintest
  - wintest2
  # - test3
ip_address_list:
  - 10.10.0.25
  - 10.10.0.26
  # - 10.10.0.27
ip_gateway_list: 
  - 10.10.0.1
  - 10.10.0.1
  # - 10.10.0.1
vsphere_datastore_list: 
  - XN_iSCSI_SSD2
  - XN_iSCSI_SSD1
  # - XN_iSCSI_SSD2
vsphere_network_list: 
  - Lab-LAN1
  - Lab-LAN1
  # - Lab-LAN1


