---
- name: Destroy Terraform
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  roles:
    - remove_hosts_inv
    - terraform_destroy

- name: Remove DNS entries from Pihole
  hosts: pihole
  gather_facts: false
  remote_user: eingram
  become: true
  become_method: sudo
  vars_files:
    - vars.yaml
  
  tasks:

    - include_role:
        name: pihole_remove

 