---
- name: Setup nginx reverse proxy
  hosts: "{{hostname}}"
  gather_facts: true
  remote_user: eingram
  become: true
  become_method: sudo

  vars_prompt:
    - name: hostname
      prompt: "Enter hostname to run against"
      private: no

  pre_tasks:

    - name: Make sure required firewall ports are open
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        zone: public
      loop:
        - 80/tcp

    - name: Reload firewall
      systemd:
        name: firewalld
        state: reloaded
        
    - when: ansible_facts['distribution'] != 'RedHat' or
            ansible_facts['distribution'] != 'Rocky'
      block:
        - name: Make sure python3-libsemanage package is installed
          ansible.builtin.package:
            name: python3-libsemanage
            state: present

        - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
          ansible.posix.seboolean:
            name: httpd_can_network_connect
            state: yes
            persistent: yes

  roles:
    - common