---
- name: Install podman and nginx reverse proxy
  hosts: "{{ hostvar }}"
  gather_facts: no
  become: true
  become_method: sudo

  tasks: 

    - name: Make sure git is installed
      package:
        name: "git"
        state: present

    - name: Make sure podman is installed
      package:
        name: "podman"
        state: present

    - name: Install nginx
      ansible.builtin.package:
        name: "nginx"
        state: present

    - name: Copy proxy.conf to /etc/nginx/conf.d
      ansible.builtin.copy:
        src: proxy.conf
        dest: /etc/nginx/conf.d
        mode: '0644'

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        enabled: yes
        state: restarted

    - name: Make sure required firewall ports are open
      become: true
      become_method: sudo
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        zone: public
      loop:
        - 80/tcp

    - name: Reload firewall
      become: true
      become_method: sudo
      systemd:
        name: firewalld
        state: reloaded

    - name: install selinux-related python binaries for Ansible to work
      package: name={{ item }} state=present
      with_items:
        - python3-libselinux
        - python3-libsemanage

    - name: set "httpd_can_network_connect" flag on
      seboolean: name={{ item }} state=yes persistent=yes
      with_items:
        - httpd_can_network_connect