---
- name: Deploy www.diversionforum.net
  hosts: yc-srv1
  gather_facts: no
  become: true
  become_method: sudo

  tasks: 

    - name: Make sure podman is installed
      package:
        name: "podman"
        state: present

    - name: Install nginx
      ansible.builtin.package:
        name: "nginx"
        state: present

    - name: Copy proxy.conf to /etc/nginx/conf.d
      ansible.builtin.copy:
        src: proxy.conf
        dest: /etc/nginx/conf.d
        mode: '0644'

    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

- name: 
  vars:
    app: "www.diversionforum.net"
    root: '/home/poduser/code/'
    repo: 'git@github.com:eingram23/'
    mysql_root: "{{ lookup('hashi_vault','secret=secret/data/dftest/mysql:root') }}"
    mysql_smfprod: "{{ lookup('hashi_vault','secret=secret/data/dftest/mysql:smfprod') }}"
    nginx_port: "8080"

  pre_tasks:
    - name: Make sure podman is installed
      become: true
      become_method: sudo
      package:
        name: "podman"
        state: present

    - name: Make sure git is installed
      become: true
      become_method: sudo
      package:  
        name: git
        state: present
    
    # - name: Allow lingering (for rootless podman)
    #   shell: "loginctl enable-linger"

  roles:
    - common
...
  