---
- name: Install podman
  hosts: docker1.local.lan
  gather_facts: no
  remote_user: eingram
  become: yes
  become_method: sudo

  tasks:

    - name: Install Podman
      package:
        name: "podman"
        state: present
        
    - name: Allow lingering (for rootless podman)
      remote_user: eingram
      become: no
      shell: "loginctl enable-linger"
