---
- name: Update software/kernel packages
  hosts: all
  remote_user: eingram
  become: yes
  become_method: sudo

  vars_prompt:
    - name: reboot
      prompt: "Reboot servers that require it? (y/n)"
      private: no
      default: "n"

  tasks:

    - when: ansible_facts['distribution'] == 'CentOS'
      block:
        - name: Install yum-utils (if needed)
          package:
            name: yum-utils

        - name: Update repo info and update installed packages - CentOS
          yum:
            name: '*'
            state: latest
            update_cache: yes

        - name: Remove unneeded packages
          yum:
            autoremove: yes

        - name: Check if reboot required (CentOS)
          command: needs-restarting -r
          register: reboot_required_centos
          ignore_errors: true
          failed_when: false
    

    - when: ansible_facts['distribution'] != 'CentOS' and 
            ansible_facts['distribution'] != 'RedHat'
      block:
        - name: Update repo info and update installed packages - (Ubuntu/Debian)
          apt:
            name: '*'
            state: latest
            update_cache: yes
            force_apt_get: yes

        - name: Remove unneeded packages
          apt:
            autoremove: yes

        - name: Check if reboot required (Ubuntu/Debian)
          stat:
            path: "/var/run/reboot-required"
          register: reboot_required_ubdeb        

    - when: ansible_facts['distribution'] == 'RedHat' 
      block:
        - name: Install dnf-utils (if needed)
          package:
            name: dnf-utils

        - name: Update repo info and update installed packages - RHEL
          dnf:
            name: '*'
            state: latest
            update_cache: yes

        - name: Remove unneeded packages
          dnf:
            autoremove: yes

        - name: Check if reboot required (RHEL)
          command: needs-restarting -r
          register: reboot_required_rhel
          ignore_errors: true
          failed_when: false

    - when: (ansible_facts['distribution'] != 'CentOS' and 
            ansible_facts['distribution'] != 'RedHat')
      block:
        - name: Report if reboot required (Ubuntu/Debian)
          debug:
            msg: "Reboot required"
          when: reboot_required_ubdeb.stat.exists
        
        - name: Reboot host (Ubuntu/Debian)
          reboot:
          when: reboot_required_ubdeb.stat.exists and
                reboot == "y"

        - name: Remove unused kernels (Non CentOS/RHEL)
          shell: apt-get purge --autoremove -y
          when: reboot_required_ubdeb.stat.exists and
                reboot == "y"


    - when: ansible_facts['distribution'] == 'CentOS'
      block:
        - name: Report if reboot required (CentOS)
          debug:  
            msg: "Reboot required"
          when: reboot_required_centos.rc != 0

        - name: Reboot host (CentOS)
          reboot:
          when: reboot_required_centos.rc != 0 and 
                reboot == "y"

        - name: Remove unused kernels (CentOS)
          shell: package-cleanup --oldkernels -y
          when: reboot_required_centos.rc != 0 and 
                reboot == "y"

    - when: ansible_facts['distribution'] == 'RedHat'
      block:
        - name: Report if reboot required (RHEL)
          debug:  
            msg: "Reboot required"
          when: reboot_required_rhel.rc != 0

        - name: Reboot host (RHEL)
          reboot:
          when: reboot_required_rhel.rc != 0 and
                reboot == "y"

        - name: Remove unused kernels (RHEL)
          shell: dnf remove --oldinstallonly -y
          when: reboot_required_rhel.rc != 0 and
                reboot == "y"
