---
- name: Deploy test.diversionforum.net
  hosts: podhost2.local.lan
  gather_facts: no
  remote_user: eingram
  become: no
  vars:
    app: 'test.diversionforum.net'
    root: '/home/eingram/code/'
    repo: 'git@github.com:eingram23/'
    mysql_root: "{{ lookup('hashi_vault','secret=secret/data/dftest/mysql:root') }}"
    mysql_smfprod: "{{ lookup('hashi_vault','secret=secret/data/dftest/mysql:smfprod') }}"

  pre_tasks:
    - name: Install Podman
      become: true
      become_method: sudo
      package:
        name: "podman"
        state: present
    
    - name: Allow lingering (for rootless podman)
      shell: "loginctl enable-linger"

  roles:
    - common
...
  