---
- name: Mount NAS share
  include_role:
    name: mount_nas

- name: Copy backup to localhost
  ansible.builtin.command: cp /mnt/Shared/Backup/Containers/unifi-controller/{{backup_filename}} /home/eingram/

- name: Stop unifi-controller container
  containers.podman.podman_container:
    name: unifi-controller
    state: stopped

- name: Restore unifi-controller data
  ansible.builtin.command: podman run --volumes-from unifi-controller --privileged --rm -v /home/eingram:/backup busybox sh -c "cd /config && tar xvf /backup/{{backup_filename}} --strip 1"

- name: Start unifi-controller container
  containers.podman.podman_container:
    name: unifi-controller
    state: started