---
- name: Deploy Terraform plan
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - vars.yaml

  # tasks:

  #   - name: Create in memory inventory
  #     add_host:
  #       name: "{{ item }}.{{ dns_suffix_list[0] }}"
  #       groups: temp_group
  #     loop: "{{ vm_name_list}}"

  roles:
    - terraform_apply
    - add_hosts_inv

- name: Create DNS entries in Pihole
  hosts: pihole
  gather_facts: false
  remote_user: eingram
  become: true
  become_method: sudo
  vars_files:
    - vars.yaml
  
  tasks:

    - include_role:
        name: pihole_add
