---
# Run with ansible-playbook deploy_new_server.yaml -kK --extra-vars "newhost=servername"
- name: Add new host Ansible inventory and copy ssh keys
  hosts: localhost
  connection: local
  # vars_prompt:
  #   - name: "hosts_prompt"
  #     prompt: "Enter new host name"
  #     private: no

  tasks:
  
#    - name: Add host temporarily
#      add_host:
#        name: "{{ hosts_prompt}}.local.lan"
#        groups: just_created

    - name: Create inventory entry
      ini_file:
        dest: /home/eingram/ansible/hosts
        section: centos
        option: "{{ newhost }}.local.lan"
        allow_no_value: yes

    - name: Refresh metadata
      meta: refresh_inventory
    
- name: Deploy Ansible keys to new host and add to inventory
  hosts: "{{ newhost }}.local.lan"
  remote_user: eingram
  become: yes
  become_method: sudo
  
  tasks:
  
    - name: Create user .ssh dir
      file:
        path: "/home/eingram/.ssh"
        state: directory

    - name: Create authorized_keys if not already existing
      file:
        path: "/home/eingram/.ssh/authorized_keys"
        state: touch

    - name: Add public key
      lineinfile:
        path: "/home/eingram/.ssh/authorized_keys"
        line: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDF/K8yVuJKbEJxbuikLQC+vok2gXqkUXhhsX6L8R6KnHIr5f1PHGiTY3aVP27BcvQmrO5TtLC+ZcC8WfHhhgvxuWmG4hk87k4vrx9e4P3fi6BXIkGe1vuBnA1Hr4FUS1te2+WmmPV0D/JDX8KkR27hDTSxp3CZKfzm7tlpKrK40/bmNJ/c/7EGxaUXAmdac22AKXEj16muJVslL8MrzM0IhcrXYFkTe9iKkbMHI9asyEJ2PN1DPYFG1D9vG1ZWHOobsig8vUkSDy7kC1AMnyBhUvC+5d+2N2S5tpuIJIabEYyU1M3MmSpSH8aFJ36f4v741sedyGz+6ObIhvi9TaORTJ58pJQlrovD950cItf4+/1KuOKJboBZN4wpKFm8zQWGIHVDjMfvGk4gmWaMVyn3+gn8pLyjLSIKj8P1aVRjJUWrpx1T+U+Rni8eSJVAyJmH1x19YwfXwX3vsEAlHdRn9sLO2At6kLCMp5WLNIOBSRPRQtZhrFljAVtmOzKHzE0= eingram@ansible1.local.lan"
